default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
test:
  <<: *default
  database: upwork_introduction_test
  username: tyger42
  password: 'SQL_SacreD42_Yasha'
development:
  <<: *default
  database: upwork_introduction_development
  username: tyger42
  password: 'SQL_SacreD42_Yasha'